"""docgen: the docs are a spreadsheet, not a document (ADR-022).

Sections that DESCRIBE the repo's state (the gate list, the flow list, the ADR
log) are DERIVED from that state, never hand-typed, so they cannot go stale.
Each lives between markers, in the README or any docs/*.md file:

    <!-- microwave:<id> start -->
    ...generated block...
    <!-- microwave:<id> end -->

docgen fills every marked section it recognizes, across all doc files, from the
source of truth. gate_docs.py then checks at commit time that the frozen text
still equals what the formula produces: a materialized view with a freshness
gate. GitHub renders static text and runs no formula on view, so we recalculate
on WRITE (at commit), not on read.

    python gates/docgen.py            # regenerate every marked section in place
    python gates/docgen.py --check    # exit 1 if any section is stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _lib import GateError, fail, ok, read_frontmatter, read_text, repo_root

GATE = "docgen"
MARKER_RE = re.compile(r"<!-- microwave:(\w+) start -->.*?<!-- microwave:\1 end -->", re.DOTALL)


def _gate_order(root: Path) -> list[str]:
    # canonical run order first (run_gates.py), then any extra gate_*.py, alpha
    rg = read_text(root / "gates" / "run_gates.py")
    ordered = re.findall(r'"(gate_\w+)\.py"', rg)
    present = sorted(p.stem for p in (root / "gates").glob("gate_*.py"))
    tail = [g for g in present if g not in ordered]
    return [g for g in ordered if g in present] + tail


def _first_docstring_desc(text: str, name: str) -> str:
    m = re.search(r'"""' + re.escape(name) + r':\s*([^\n"]+)', text)
    return (m.group(1).strip().rstrip(".") if m else "(no description)")


def gen_gates(root: Path) -> str:
    rows = ["| Gate | Guarantee |", "|---|---|"]
    for name in _gate_order(root):
        desc = _first_docstring_desc(read_text(root / "gates" / f"{name}.py"), name)
        rows.append(f"| `{name}` | {desc} |")
    return "\n".join(rows)


def gen_flows(root: Path) -> str:
    rows = ["| Flow | Purpose |", "|---|---|"]
    for f in sorted((root / "flows").glob("*.md")):
        m = re.search(r"^#\s*Flow:\s*(.+?)\s*\((.+?)\)\s*$", read_text(f), re.MULTILINE)
        name, purpose = (m.group(1).strip(), m.group(2).strip()) if m else (f.stem, "")
        rows.append(f"| `{name}` | {purpose} |")
    return "\n".join(rows)


def gen_adrs(root: Path) -> str:
    rows = ["| ADR | Decision | Status |", "|---|---|---|"]
    entries = []
    for f in sorted((root / "wiki" / "adr").glob("ADR-*.md")):
        fm, _ = read_frontmatter(f)
        entries.append((str(fm.get("id", f.stem)), str(fm.get("title", "")),
                        str(fm.get("status", ""))))
    for aid, title, status in sorted(entries):
        rows.append(f"| {aid} | {title} | {status} |")
    return "\n".join(rows)


# marker id -> generator. Add a section by adding a pair here and its markers
# in any doc file; the mechanism does not change (ADR-022).
SECTIONS = {"gates": gen_gates, "flows": gen_flows, "adrs": gen_adrs}


def _doc_files(root: Path) -> list[Path]:
    files = [root / "README.md", *sorted((root / "docs").glob("*.md"))]
    return [f for f in files if f.exists()]


def apply(root: Path, check: bool) -> list[str]:
    """Regenerate (or, if check, only compare) every recognized marked section
    across all doc files. Returns the list of stale 'file:section' ids."""
    stale: list[str] = []
    for doc in _doc_files(root):
        text = read_text(doc)
        if "<!-- microwave:" not in text:
            continue

        def repl(m: re.Match, doc: Path = doc) -> str:
            section = m.group(1)
            if section not in SECTIONS:
                raise GateError(f"{doc.name}: unknown generated section "
                                f"'{section}' (no generator in docgen.SECTIONS)")
            start, end = f"<!-- microwave:{section} start -->", f"<!-- microwave:{section} end -->"
            replacement = (f"{start}\n<!-- generated by gates/docgen.py, do not "
                           f"edit by hand -->\n\n{SECTIONS[section](root)}\n\n{end}")
            if m.group(0).strip() != replacement.strip():
                stale.append(f"{doc.name}:{section}")
            return replacement

        new = MARKER_RE.sub(repl, text)
        if not check and new != text:
            doc.write_text(new, encoding="utf-8", newline="\n")
    return stale


def main(argv: list[str]) -> None:
    root = repo_root()
    check = "--check" in argv
    stale = apply(root, check=check)
    if check:
        if stale:
            fail(GATE, f"docs stale in: {', '.join(stale)}. "
                       f"Run `python gates/docgen.py` and commit.")
        ok(GATE, "generated doc sections are fresh")
    else:
        ok(GATE, f"docs regenerated ({len(SECTIONS)} section type(s))")


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except GateError as e:
        fail(GATE, str(e))
